---

- hosts: "{{ hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: 'Install Git client'
      yum:
        name: git
        state: present

    - name: 'Install httpd apache'
      yum:
        name: httpd
        state: present

    - name: 'Start and enable Apache'
      service:
        name: httpd
        status: started
        enabled: yes
      become: yes
