---

- hosts: "{{ hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root

  tasks:

    - name: 'Generate SSH keypair'
      openssh_keypair:
        path: '/home/ec2-user/.ssh/id_rsa'
        type: rsa
        size: 2048
        group: ec2-user
        owner: ec2-user

    - name: 'Add own key to authorized_keys file'
      shell: 'cat /home/ec2-user/.ssh/id_rsa_pub >> /home/ec2-user/.ssh/authorized_keys && chmod 600 /home/ec2-user/.ssh/authorized_keys'

    - name: 'Copy over Jenkins worker creation payload xml'
      vars:
        ipv4: '{{ ansible_default_ipv4.address }}'
      template:
        src: 'node.j2'
        dest: '/home/ec2-user/node.xml'
        owner: ec2-user
        mode: '0644'